on: [push]

name: naisc-build

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "Ubuntu-latest"
          prerelease: true
          title: "Latest Build"
          files: |
            naisc-meas/target/naisc-meas-jar-with-dependencies.jar
            naisc-core/target/naisc-core-1.1-jar-with-dependencies.jar
